### ISSUE TITLE
[TheWitcher] New Melee attack shortcuts (from Equipped Weapons section) doesn't work from Quick Weapon buttons

### ISSUE THREAD

**Issue by gnompsky** [Stexinator/roll20-character-sheets#339]
These ones don't take the "Used Skill" select:
![image](https://user-images.githubusercontent.com/2944741/180621414-1835b077-1f2d-4550-9e00-ab34a30bf335.png)

**Comment by Stexinator** [comment]
Fixed by https://github.com/Roll20/roll20-character-sheets/pull/10831
